#!/bin/bash
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"
gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface clock-format 12h
gsettings set org.gnome.desktop.interface cursor-blink false
