#!/usr/bin/env bash
ln -sfr vim $HOME/.vim
ln -sfr fontconfig $HOME/.config/fontconfig
ln -sfr tmux.conf $HOME/.tmux.conf
ln -sfr vimrc $HOME/.vimrc
ln -sfr fonts $HOME/.fonts
ln -sfr bashrc $HOME/.bashrc
mkdir $HOME/.tmp
